### ISSUE TITLE
Billing Remark #4

### ISSUE THREAD

**Issue by twgreg** [TaxwareSupport/Issue-Reports#98] opened 2019-01-21 22:02 UTC
**Client Name:**  
Jamie

**Client ID:**  
21176

**Description:**  
Remark #4 is being duplicated in the invoice.
She has a message on Remark 4 in the Billing setup.
When she creates an invoice inside the client, the remark shows up twice in print.
She can delete the remark from the invoice input and it will print with the message only once.

**Reproduce:**  
I tested on mine and got the same result.
I put a message in Remark #4 in the billing setup and the invoice printed it twice.

**Data Location:**

**Comment by MyNameIsDonovan** [comment] 2019-05-03 15:40
Hey is this still a thing? I just testing and cant reproduce

**Comment by MyNameIsDonovan** [comment] 2019-05-03 16:09
closing this for now, I think it was already fixed

**Closed by MyNameIsDonovan** 2019-05-03 16:09 UTC
Labels: Individual
