### ISSUE TITLE
Billing defaults aren't defaulting to the clients

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#105] opened 2019-01-22 16:19 UTC
**Client Name:**  
Chris
**Client ID:**  
5980
**Description:**  
When starting a new return billing defaults are not added to the the client. All bills show zero and print boxes are checked even if not checked in defaults. This is fixed if you click restore defaults. 
**Reproduce:**  

**Data Location:**

**Comment by MyNameIsDonovan** [comment] 2019-01-22 16:55
¯\_(ツ)_/¯
I cant reproduce. Let me know what you come up with

**Comment by MyNameIsDonovan** [comment] 2019-01-22 17:54
Kk found the problem, its fixed now

**Closed by MyNameIsDonovan** 2019-01-22 17:54 UTC
